name: Update RSS Content

on:
  schedule:
    - cron: '0 1 * * *'  # 每天在UTC时间1:00运行（对应北京时间9:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  update-content:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser PyGithub pytz translators
    
    - name: Run update script
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: python create.py